---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: cv_template.tex
    # pandoc_args: [
    #   "-V", "classoption=twocolumn"
    # ]
geometry: margin=1in
# classoption: 
# - twocolumn

title: "CV"
author: Lukas Warode
jobtitle: "B.A. Political Science | M.Sc. Data Science for Public Policy Candidate"
#address: "Invalidenstraße 135 · 10115 Berlin · Germany"
fontawesome: yes
email: lukas.warode@gmx.de
linkedin: lukas-warode-64a84a1a3
linkedin_name: Lukas Warode
github: lwarode
twitter: lukas_warode
#osf: "Enter 5 digit osf string here"
#phone: "+353 1 408 4800"
web: lwarode.github.io
updated: no

# keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# Education

*Hertie School*, M.Sc. Data Science for Public Policy \hfill 2021 -- 2023

- **Covered Areas as yet**

  - · Data Science with `R` and `Python`
  - · Machine Learning and its Mathematical Foundations
  - · Economics
  - · Public Policy and the Policy Process
  - · International Law
  

*University of Bremen*, B.A. Political Science (Grade: 1.37) \hfill 2017 -- 2021

- Strongly above-average grades (part of the best 2% of the cohort)

- Thesis: "The 2014 and 2019 European Elections in the Context of Second-Order
Elections" (Grade: 1.0)

- **Focus Areas**

  - · (Applied) Statistics and Quantitative Methods
  - · Comparative Politics
  - · Election and Party Research
  - · Political Economy

*Queen's University Belfast*, Exchange Semester \hfill 2019

\vspace{15pt}
\hrule
\vspace{5pt}
<!-- \rule{\textwidth}{0.75pt} -->

# Work Experience

## **Academia**

Research Assistant, *WZB Berlin Social Science Center* \hfill 10/2021 -- 05/2022

- · Project [*Transformations of Democracy*](https://www.wzb.eu/en/research/dynamics-of-political-systems/transformations-of-democracy)

  - Prof. Daniel Ziblatt, Ph.D.

Tutor in Statistics, *University of Bremen · Faculty of Social Sciences* \hfill 11/2020 -- 03/2021

Research Assistant, *University of Bremen · SOCIUM* \hfill 03/2018 -- 12/2020

- · Project [*Careers in Comparison*](https://parliamentarycareersincomparison.org/)

  - Prof. Dr. Philip Manow & Dr. Valentin Schröder

- · Project [*ParlGov*](http://www.parlgov.org/)

  - Dr. Holger Döring & Prof. Dr. Philip Manow
  
- · Preparing lecture "Introduction to Comparative Politics"

- · Assisting a research paper

  - Dr. Alexander Gattig & Prof. Dr. Philip Manow

## **Private Sector**

Data Science & Research Intern, [*Project Open Discourse*](https://opendiscourse.de) -- [*Limebit*](https://limebit.de) \hfill 07/2022 -- 08/2022

Data Journalism Intern, *Süddeutsche Zeitung* \hfill 06/2021 -- 07/2021

Data Science Intern, *eoda GmbH* \hfill 01/2021 -- 03/2021

Graphic Design Intern, *liauw konzept und design* \hfill 10/2016 -- 01/2017

\vspace{15pt}
\hrule
\vspace{5pt}
<!-- \rule{\textwidth}{0.75pt} -->

# Volunteering

Student Representative, *Hertie School · Master of Data Sciene for Public Policy* \hfill 09/2022 -- *today*

CorrelAid (*Data Science for Good*) \hfill 06/2019 -- *today*

- · Organizing the [*Local Chapter Bremen*](https://correlaid.org/correlaid-x/bremen/)

- · Participating in voluntary Data Science projects

- · Presenting (Political) Data Science projects at "Data Meetups"

Member of the appointment committee, *Professorship for Quantitative Methods*, 
\break 
*University of Bremen · Faculty of Social Sciences* \hfill 10/2020

Voluntary activity as an election worker, *State of Bremen* \hfill 05/2019

Voluntary involvement in a community as a group leader, *St. Raphael Bremen* \hfill 2015 -- 2017

\vspace{15pt}
\hrule
\vspace{5pt}
<!-- \rule{\textwidth}{0.75pt} -->

# Skills

## **Language**

German (mother tongue)

English (fluent | TOEFL iBT · Score: 110/120 · C1 -- C2)

French (basics)

## **Statistical Packages**

`R` / *tidyverse* (advanced to semi-professional)

- · Data manipulation
- · Data visualization
- · Statistical methods
- · Interactive tools (`R Markdown`, `Shiny`)
- · Project and package development

Stata (advanced)

Mplus (basics)

## **Computer Knowledge**

`Python` (basics to advanced)

- · Data manipulation
- · Data visualization
- · Machine Learning methods

`SQL` (basics)

MS Office -- Word, Excel, PowerPoint (basics -- advanced)

Adobe Creative Cloud - InDesign, Photoshop, Illustrator, Dreamweaver, Lightroom (basics -- advanced)

```{r mapping skills, fig.height = 3, fig.width = 9, echo=FALSE, include=FALSE}
library(ggplot2)
library(tibble)
library(dplyr)

r_skills <- tribble(
  ~ Skill, ~ Level,
  "Data Visualisation", 4,
  "Data Manipulation", 4,
  "Statistical Methods", 3,
  "R Markdown", 3,
  "Advanced Programming", 2
) %>%
  tidyr::pivot_wider(names_from = "Skill", values_from = Level)
```

\vspace{15pt}
\hrule
\vspace{5pt}

# Publications and Projects

## *Published*

### **Data Science Projects**

[`opendiscouRse`](https://github.com/open-discourse/opendiscouRse): `R Package` using [*Open Discourse*](https://opendiscourse.de) database

- · Package containing functions to obtain descriptive statistics and analyses for external and internal usage
- · Current state: In development

[ParlGov Dashboard](https://lukas-warode.shinyapps.io/ParlGov_Dashboard/): `R Shiny` Dashboard using [*ParlGov*](http://www.parlgov.org/) database

- · Comprehensive data visualizations and tables on parties, elections and cabinets
- · [Source Code](https://github.com/lwarode/ParlGov_Dashboard)

[`legislatoR+`](https://687qak-gamesluxx.shinyapps.io/legislatoRplus/): `R Shiny` App using [Comparative Legislators Database](https://www.cambridge.org/core/journals/british-journal-of-political-science/article/comparative-legislators-database/D28BB58A8B2C08C8593DB741F42C18B2)

- · Master's class final course project, geographical and distributional visualizations of German MPs
- · [Source Code and Project Description](https://github.com/benediktstroebl/legislatoRplus)

[Whisky Dashboard](https://lukas-warode.shinyapps.io/whisky_dashboard/): `R Shiny` App using taste data on Scottish Single Malt Whiskies

- · Categorical and geographical visualizations
- · [Source Code and further Analyses](https://github.com/lwarode/whisky_data)

### **Articles**

[Schnelltests liefern mangelhafte Ergebnisse](https://projekte.sueddeutsche.de/artikel/politik/schnelltests-mangelhaft-e425074/?reduced=true), *Süddeutsche Zeitung*, co-author: Markus Hametner

[Warum die Impfkampagne stockt](https://www.sueddeutsche.de/wissen/impfkampagne-impftempo-astra-zeneca-biontech-corona-1.5345276?reduced=true), *Süddeutsche Zeitung*, co-authors: Simon Groß, Berit Kruse and Sören Müller-Hansen

## *Prospective*

Publication of *Open Discourse* Data Paper in peer-reviewed journal


